// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsdb_plugin.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	tsdb_plugin.proto

It has these top-level messages:
	TsdbQuery
	Query
	TimeRange
	Response
	QueryResult
	Table
	TableColumn
	TableRow
	RowValue
	DatasourceInfo
	TimeSeries
	Point
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RowValue_Kind int32

const (
	// Field type unknown.
	RowValue_TYPE_UNKNOWN RowValue_Kind = 0
	// Field type null.
	RowValue_TYPE_NULL RowValue_Kind = 1
	// Field type float.
	RowValue_TYPE_FLOAT RowValue_Kind = 2
	// Field type int64.
	RowValue_TYPE_INT64 RowValue_Kind = 3
	// Field type bool.
	RowValue_TYPE_BOOL RowValue_Kind = 4
	// Field type string.
	RowValue_TYPE_STRING RowValue_Kind = 5
	// Field type bytes.
	RowValue_TYPE_BYTES RowValue_Kind = 6
)

var RowValue_Kind_name = map[int32]string{
	0: "TYPE_UNKNOWN",
	1: "TYPE_NULL",
	2: "TYPE_FLOAT",
	3: "TYPE_INT64",
	4: "TYPE_BOOL",
	5: "TYPE_STRING",
	6: "TYPE_BYTES",
}
var RowValue_Kind_value = map[string]int32{
	"TYPE_UNKNOWN": 0,
	"TYPE_NULL":    1,
	"TYPE_FLOAT":   2,
	"TYPE_INT64":   3,
	"TYPE_BOOL":    4,
	"TYPE_STRING":  5,
	"TYPE_BYTES":   6,
}

func (x RowValue_Kind) String() string {
	return proto1.EnumName(RowValue_Kind_name, int32(x))
}
func (RowValue_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type TsdbQuery struct {
	TimeRange  *TimeRange      `protobuf:"bytes,1,opt,name=timeRange" json:"timeRange,omitempty"`
	Datasource *DatasourceInfo `protobuf:"bytes,2,opt,name=datasource" json:"datasource,omitempty"`
	Queries    []*Query        `protobuf:"bytes,3,rep,name=queries" json:"queries,omitempty"`
}

func (m *TsdbQuery) Reset()                    { *m = TsdbQuery{} }
func (m *TsdbQuery) String() string            { return proto1.CompactTextString(m) }
func (*TsdbQuery) ProtoMessage()               {}
func (*TsdbQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TsdbQuery) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *TsdbQuery) GetDatasource() *DatasourceInfo {
	if m != nil {
		return m.Datasource
	}
	return nil
}

func (m *TsdbQuery) GetQueries() []*Query {
	if m != nil {
		return m.Queries
	}
	return nil
}

type Query struct {
	RefId         string `protobuf:"bytes,1,opt,name=refId" json:"refId,omitempty"`
	MaxDataPoints int64  `protobuf:"varint,2,opt,name=maxDataPoints" json:"maxDataPoints,omitempty"`
	IntervalMs    int64  `protobuf:"varint,3,opt,name=intervalMs" json:"intervalMs,omitempty"`
	ModelJson     string `protobuf:"bytes,4,opt,name=modelJson" json:"modelJson,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto1.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Query) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *Query) GetMaxDataPoints() int64 {
	if m != nil {
		return m.MaxDataPoints
	}
	return 0
}

func (m *Query) GetIntervalMs() int64 {
	if m != nil {
		return m.IntervalMs
	}
	return 0
}

func (m *Query) GetModelJson() string {
	if m != nil {
		return m.ModelJson
	}
	return ""
}

type TimeRange struct {
	FromRaw     string `protobuf:"bytes,1,opt,name=fromRaw" json:"fromRaw,omitempty"`
	ToRaw       string `protobuf:"bytes,2,opt,name=toRaw" json:"toRaw,omitempty"`
	FromEpochMs int64  `protobuf:"varint,3,opt,name=fromEpochMs" json:"fromEpochMs,omitempty"`
	ToEpochMs   int64  `protobuf:"varint,4,opt,name=toEpochMs" json:"toEpochMs,omitempty"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto1.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TimeRange) GetFromRaw() string {
	if m != nil {
		return m.FromRaw
	}
	return ""
}

func (m *TimeRange) GetToRaw() string {
	if m != nil {
		return m.ToRaw
	}
	return ""
}

func (m *TimeRange) GetFromEpochMs() int64 {
	if m != nil {
		return m.FromEpochMs
	}
	return 0
}

func (m *TimeRange) GetToEpochMs() int64 {
	if m != nil {
		return m.ToEpochMs
	}
	return 0
}

type Response struct {
	Results []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto1.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type QueryResult struct {
	Error    string        `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	RefId    string        `protobuf:"bytes,2,opt,name=refId" json:"refId,omitempty"`
	MetaJson string        `protobuf:"bytes,3,opt,name=metaJson" json:"metaJson,omitempty"`
	Series   []*TimeSeries `protobuf:"bytes,4,rep,name=series" json:"series,omitempty"`
	Tables   []*Table      `protobuf:"bytes,5,rep,name=tables" json:"tables,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto1.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *QueryResult) GetRefId() string {
	if m != nil {
		return m.RefId
	}
	return ""
}

func (m *QueryResult) GetMetaJson() string {
	if m != nil {
		return m.MetaJson
	}
	return ""
}

func (m *QueryResult) GetSeries() []*TimeSeries {
	if m != nil {
		return m.Series
	}
	return nil
}

func (m *QueryResult) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type Table struct {
	Columns []*TableColumn `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Rows    []*TableRow    `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto1.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Table) GetColumns() []*TableColumn {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Table) GetRows() []*TableRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type TableColumn struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TableColumn) Reset()                    { *m = TableColumn{} }
func (m *TableColumn) String() string            { return proto1.CompactTextString(m) }
func (*TableColumn) ProtoMessage()               {}
func (*TableColumn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TableColumn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TableRow struct {
	Values []*RowValue `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *TableRow) Reset()                    { *m = TableRow{} }
func (m *TableRow) String() string            { return proto1.CompactTextString(m) }
func (*TableRow) ProtoMessage()               {}
func (*TableRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TableRow) GetValues() []*RowValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type RowValue struct {
	Kind        RowValue_Kind `protobuf:"varint,1,opt,name=kind,enum=plugins.RowValue_Kind" json:"kind,omitempty"`
	FloatValue  float32       `protobuf:"fixed32,2,opt,name=floatValue" json:"floatValue,omitempty"`
	Int64Value  int64         `protobuf:"varint,3,opt,name=int64Value" json:"int64Value,omitempty"`
	BoolValue   bool          `protobuf:"varint,4,opt,name=boolValue" json:"boolValue,omitempty"`
	StringValue string        `protobuf:"bytes,5,opt,name=stringValue" json:"stringValue,omitempty"`
	BytesValue  []byte        `protobuf:"bytes,6,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
}

func (m *RowValue) Reset()                    { *m = RowValue{} }
func (m *RowValue) String() string            { return proto1.CompactTextString(m) }
func (*RowValue) ProtoMessage()               {}
func (*RowValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RowValue) GetKind() RowValue_Kind {
	if m != nil {
		return m.Kind
	}
	return RowValue_TYPE_UNKNOWN
}

func (m *RowValue) GetFloatValue() float32 {
	if m != nil {
		return m.FloatValue
	}
	return 0
}

func (m *RowValue) GetInt64Value() int64 {
	if m != nil {
		return m.Int64Value
	}
	return 0
}

func (m *RowValue) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *RowValue) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *RowValue) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

type DatasourceInfo struct {
	Id             int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OrgId          int64  `protobuf:"varint,2,opt,name=orgId" json:"orgId,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Type           string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Url            string `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	JsonData       string `protobuf:"bytes,6,opt,name=jsonData" json:"jsonData,omitempty"`
	SecureJsonData string `protobuf:"bytes,7,opt,name=secureJsonData" json:"secureJsonData,omitempty"`
}

func (m *DatasourceInfo) Reset()                    { *m = DatasourceInfo{} }
func (m *DatasourceInfo) String() string            { return proto1.CompactTextString(m) }
func (*DatasourceInfo) ProtoMessage()               {}
func (*DatasourceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DatasourceInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DatasourceInfo) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DatasourceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatasourceInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DatasourceInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DatasourceInfo) GetJsonData() string {
	if m != nil {
		return m.JsonData
	}
	return ""
}

func (m *DatasourceInfo) GetSecureJsonData() string {
	if m != nil {
		return m.SecureJsonData
	}
	return ""
}

type TimeSeries struct {
	Name   string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tags   map[string]string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points []*Point          `protobuf:"bytes,3,rep,name=points" json:"points,omitempty"`
}

func (m *TimeSeries) Reset()                    { *m = TimeSeries{} }
func (m *TimeSeries) String() string            { return proto1.CompactTextString(m) }
func (*TimeSeries) ProtoMessage()               {}
func (*TimeSeries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TimeSeries) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TimeSeries) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TimeSeries) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	Timestamp int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Value     float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto1.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Point) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Point) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto1.RegisterType((*TsdbQuery)(nil), "plugins.TsdbQuery")
	proto1.RegisterType((*Query)(nil), "plugins.Query")
	proto1.RegisterType((*TimeRange)(nil), "plugins.TimeRange")
	proto1.RegisterType((*Response)(nil), "plugins.Response")
	proto1.RegisterType((*QueryResult)(nil), "plugins.QueryResult")
	proto1.RegisterType((*Table)(nil), "plugins.Table")
	proto1.RegisterType((*TableColumn)(nil), "plugins.TableColumn")
	proto1.RegisterType((*TableRow)(nil), "plugins.TableRow")
	proto1.RegisterType((*RowValue)(nil), "plugins.RowValue")
	proto1.RegisterType((*DatasourceInfo)(nil), "plugins.DatasourceInfo")
	proto1.RegisterType((*TimeSeries)(nil), "plugins.TimeSeries")
	proto1.RegisterType((*Point)(nil), "plugins.Point")
	proto1.RegisterEnum("plugins.RowValue_Kind", RowValue_Kind_name, RowValue_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TsdbPlugin service

type TsdbPluginClient interface {
	Query(ctx context.Context, in *TsdbQuery, opts ...grpc.CallOption) (*Response, error)
}

type tsdbPluginClient struct {
	cc *grpc.ClientConn
}

func NewTsdbPluginClient(cc *grpc.ClientConn) TsdbPluginClient {
	return &tsdbPluginClient{cc}
}

func (c *tsdbPluginClient) Query(ctx context.Context, in *TsdbQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/plugins.TsdbPlugin/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TsdbPlugin service

type TsdbPluginServer interface {
	Query(context.Context, *TsdbQuery) (*Response, error)
}

func RegisterTsdbPluginServer(s *grpc.Server, srv TsdbPluginServer) {
	s.RegisterService(&_TsdbPlugin_serviceDesc, srv)
}

func _TsdbPlugin_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TsdbQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsdbPluginServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugins.TsdbPlugin/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsdbPluginServer).Query(ctx, req.(*TsdbQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _TsdbPlugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "plugins.TsdbPlugin",
	HandlerType: (*TsdbPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _TsdbPlugin_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tsdb_plugin.proto",
}

func init() { proto1.RegisterFile("tsdb_plugin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0x5d, 0x93, 0xdb, 0x34,
	0x14, 0xc5, 0x5f, 0x49, 0x7c, 0xd3, 0x06, 0x57, 0x74, 0x20, 0xb3, 0x03, 0xcc, 0xe2, 0x81, 0xce,
	0x02, 0x33, 0x19, 0x58, 0x4a, 0xcb, 0x14, 0x5e, 0x58, 0x08, 0x4c, 0xda, 0x90, 0x2c, 0x5a, 0x17,
	0xa6, 0x3c, 0xd0, 0x71, 0x12, 0x25, 0x98, 0xda, 0x56, 0x90, 0xe4, 0x0d, 0x19, 0x9e, 0xf8, 0x27,
	0x3c, 0xf3, 0xcc, 0xff, 0xe0, 0x2f, 0x75, 0x74, 0x2d, 0x7f, 0x24, 0xdd, 0x27, 0xfb, 0x9e, 0x73,
	0x24, 0x5d, 0x5d, 0x1d, 0x5d, 0xc1, 0x1d, 0x25, 0x57, 0x8b, 0xe7, 0xdb, 0xb4, 0xd8, 0x24, 0xf9,
	0x68, 0x2b, 0xb8, 0xe2, 0xa4, 0x5b, 0x46, 0x32, 0xfc, 0xc7, 0x02, 0x3f, 0x92, 0xab, 0xc5, 0x8f,
	0x05, 0x13, 0x7b, 0xf2, 0x09, 0xf8, 0x2a, 0xc9, 0x18, 0x8d, 0xf3, 0x0d, 0x1b, 0x5a, 0xa7, 0xd6,
	0x59, 0xff, 0x9c, 0x8c, 0x8c, 0x74, 0x14, 0x55, 0x0c, 0x6d, 0x44, 0xe4, 0x21, 0xc0, 0x2a, 0x56,
	0xb1, 0xe4, 0x85, 0x58, 0xb2, 0xa1, 0x8d, 0x43, 0xde, 0xaa, 0x87, 0x7c, 0x5b, 0x53, 0x93, 0x7c,
	0xcd, 0x69, 0x4b, 0x4a, 0xce, 0xa0, 0xfb, 0x47, 0xc1, 0x44, 0xc2, 0xe4, 0xd0, 0x39, 0x75, 0xce,
	0xfa, 0xe7, 0x83, 0x7a, 0x14, 0xe6, 0x42, 0x2b, 0x3a, 0xfc, 0xdb, 0x02, 0xaf, 0x4c, 0xef, 0x2e,
	0x78, 0x82, 0xad, 0x27, 0x2b, 0x4c, 0xcd, 0xa7, 0x65, 0x40, 0xde, 0x87, 0xdb, 0x59, 0xfc, 0xa7,
	0x5e, 0xea, 0x92, 0x27, 0xb9, 0x92, 0x98, 0x85, 0x43, 0x0f, 0x41, 0xf2, 0x2e, 0x40, 0x92, 0x2b,
	0x26, 0xae, 0xe3, 0xf4, 0x07, 0xbd, 0xa4, 0x96, 0xb4, 0x10, 0xf2, 0x36, 0xf8, 0x19, 0x5f, 0xb1,
	0xf4, 0xb1, 0xe4, 0xf9, 0xd0, 0xc5, 0xf9, 0x1b, 0x20, 0xfc, 0x0b, 0xfc, 0x7a, 0xfb, 0x64, 0x08,
	0xdd, 0xb5, 0xe0, 0x19, 0x8d, 0x77, 0x26, 0x91, 0x2a, 0xd4, 0x09, 0x2a, 0xae, 0x71, 0xbb, 0x4c,
	0x10, 0x03, 0x72, 0x0a, 0x7d, 0x2d, 0x18, 0x6f, 0xf9, 0xf2, 0xb7, 0x7a, 0xed, 0x36, 0xa4, 0x17,
	0x57, 0xbc, 0xe2, 0x5d, 0xe4, 0x1b, 0x20, 0x7c, 0x04, 0x3d, 0xca, 0xe4, 0x96, 0xe7, 0x92, 0x91,
	0x11, 0x74, 0x05, 0x93, 0x45, 0xaa, 0xe4, 0xd0, 0xc2, 0xb2, 0xdd, 0x3d, 0x2a, 0x1b, 0x92, 0xb4,
	0x12, 0x85, 0xff, 0x5a, 0xd0, 0x6f, 0x11, 0x3a, 0x43, 0x26, 0x04, 0x17, 0x55, 0x09, 0x31, 0x68,
	0x0a, 0x6b, 0xb7, 0x0b, 0x7b, 0x02, 0xbd, 0x8c, 0xa9, 0x18, 0x2b, 0xe2, 0x20, 0x51, 0xc7, 0xe4,
	0x63, 0xe8, 0xc8, 0xf2, 0xf4, 0x5c, 0x4c, 0xe3, 0x8d, 0x03, 0x9b, 0x5c, 0x21, 0x45, 0x8d, 0x84,
	0xdc, 0x83, 0x8e, 0x8a, 0x17, 0x29, 0x93, 0x43, 0xef, 0xe8, 0xa8, 0x23, 0x0d, 0x53, 0xc3, 0x86,
	0xbf, 0x82, 0x87, 0x80, 0xde, 0xe5, 0x92, 0xa7, 0x45, 0x96, 0xbf, 0xba, 0x4b, 0x14, 0x7c, 0x83,
	0x24, 0xad, 0x44, 0xe4, 0x03, 0x70, 0x05, 0xdf, 0xe9, 0x93, 0xd7, 0xe2, 0x3b, 0x47, 0xd3, 0xf3,
	0x1d, 0x45, 0x3a, 0x7c, 0x0f, 0xfa, 0xad, 0xe1, 0x84, 0x80, 0x9b, 0xc7, 0x19, 0x33, 0xa5, 0xc0,
	0xff, 0xf0, 0x73, 0xe8, 0x55, 0x83, 0xc8, 0x87, 0xd0, 0xb9, 0x8e, 0xd3, 0x82, 0x55, 0x49, 0x34,
	0xf3, 0x52, 0xbe, 0xfb, 0x49, 0x33, 0xd4, 0x08, 0xc2, 0xff, 0x6d, 0xe8, 0x55, 0x20, 0xf9, 0x08,
	0xdc, 0x17, 0x49, 0x5e, 0xba, 0x74, 0x70, 0xfe, 0xe6, 0x2b, 0xa3, 0x46, 0x4f, 0x92, 0x7c, 0x45,
	0x51, 0xa3, 0x6d, 0xb9, 0x4e, 0x79, 0xac, 0x90, 0xc0, 0xf2, 0xdb, 0xb4, 0x85, 0x18, 0xdb, 0x3e,
	0xb8, 0x5f, 0xf2, 0x8d, 0x6d, 0x0d, 0xa2, 0x9d, 0xb3, 0xe0, 0x3c, 0x2d, 0x69, 0xed, 0x9c, 0x1e,
	0x6d, 0x00, 0xed, 0x3c, 0xa9, 0x44, 0x92, 0x6f, 0x4a, 0xde, 0xc3, 0x8d, 0xb6, 0x21, 0x3d, 0xff,
	0x62, 0xaf, 0x98, 0x2c, 0x05, 0x9d, 0x53, 0xeb, 0xec, 0x16, 0x6d, 0x21, 0xe1, 0x0e, 0x5c, 0x9d,
	0x2d, 0x09, 0xe0, 0x56, 0xf4, 0xec, 0x72, 0xfc, 0xfc, 0xe9, 0xec, 0xc9, 0x6c, 0xfe, 0xf3, 0x2c,
	0x78, 0x8d, 0xdc, 0x06, 0x1f, 0x91, 0xd9, 0xd3, 0xe9, 0x34, 0xb0, 0xc8, 0x00, 0x00, 0xc3, 0xef,
	0xa6, 0xf3, 0xaf, 0xa3, 0xc0, 0xae, 0xe3, 0xc9, 0x2c, 0x7a, 0x70, 0x3f, 0x70, 0x6a, 0xf9, 0xc5,
	0x7c, 0x3e, 0x0d, 0x5c, 0xf2, 0x3a, 0xf4, 0x31, 0xbc, 0x8a, 0xe8, 0x64, 0xf6, 0x7d, 0xe0, 0xd5,
	0xfa, 0x8b, 0x67, 0xd1, 0xf8, 0x2a, 0xe8, 0x84, 0xff, 0x59, 0x30, 0x38, 0x6c, 0x1f, 0x64, 0x00,
	0x76, 0x52, 0x56, 0xd5, 0xa1, 0x76, 0xb2, 0xd2, 0xae, 0xe5, 0x62, 0x63, 0x5c, 0xeb, 0xd0, 0x32,
	0xa8, 0x4f, 0xd5, 0x69, 0x4e, 0x55, 0x63, 0x6a, 0xbf, 0x65, 0xe6, 0x5e, 0xe3, 0x3f, 0x09, 0xc0,
	0x29, 0x44, 0x6a, 0x6a, 0xa2, 0x7f, 0xb5, 0xdf, 0x7f, 0x97, 0x3c, 0xd7, 0xab, 0x62, 0x25, 0x7c,
	0x5a, 0xc7, 0xe4, 0x1e, 0x0c, 0x24, 0x5b, 0x16, 0x82, 0x3d, 0xae, 0x14, 0x5d, 0x54, 0x1c, 0xa1,
	0x3a, 0x6d, 0x68, 0x6e, 0xc0, 0x4d, 0x16, 0x23, 0x9f, 0x82, 0xab, 0xe2, 0x4d, 0x65, 0xd6, 0x77,
	0x6e, 0xb8, 0x38, 0xa3, 0x28, 0xde, 0xc8, 0x71, 0xae, 0xc4, 0x9e, 0xa2, 0x54, 0x5f, 0xa0, 0x6d,
	0xd9, 0xdb, 0x8e, 0x7b, 0x25, 0x76, 0x37, 0x6a, 0xd8, 0x93, 0x87, 0xe0, 0xd7, 0x43, 0xf5, 0x06,
	0x5f, 0xb0, 0xbd, 0x59, 0x5a, 0xff, 0xea, 0x82, 0x5d, 0xd7, 0x3e, 0xf3, 0x69, 0x19, 0x3c, 0xb2,
	0xbf, 0xb0, 0xc2, 0x2f, 0xc1, 0xc3, 0x99, 0xb0, 0x13, 0x25, 0x19, 0x93, 0x2a, 0xce, 0xb6, 0xa6,
	0xd4, 0x0d, 0x70, 0x38, 0x81, 0x65, 0x26, 0x38, 0xff, 0x0a, 0x40, 0x3f, 0x21, 0x97, 0x98, 0x12,
	0x19, 0x55, 0xdd, 0xba, 0xf5, 0x72, 0x54, 0x0f, 0xcc, 0x49, 0xeb, 0x0a, 0x99, 0x8e, 0x76, 0xd1,
	0xfd, 0xc5, 0xc3, 0x37, 0x69, 0xd1, 0xc1, 0xcf, 0x67, 0x2f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xef,
	0xec, 0xa7, 0x13, 0xaf, 0x06, 0x00, 0x00,
}
